#!/bin/python3
version = "1.1.1"

import sys
import os
import json
try:
    import webchk
except Exception:
    print("[ERROR] Webchk not found X_X")
    sys.exit()

try:
    from colorama import Fore
except Exception:
    print("[ERROR] Colorama not found X_X")
    sys.exit()

if not os.path.exists("/etc/fpac/main.repo"):
    print("[ERROR] No main repo X_X")
    sys.exit()

f = open("/etc/fpac/main.repo","r")
data = json.loads(f.read())
f.close()
packages = data["packages"]
sources = data["sources"]
libraries = data["libraries"]
LSources = data["LSources"]
links = data["links"]
PYTHONPATH = os.getenv("PYTHONPATH")

if PYTHONPATH == "":
    print("[ERROR] Your PYTHONPATH is empty X_X")
    sys.exit()

if not webchk.check(sources[0]):
    print("[ERROR] The main repo could not be pinged X_X")
    sys.exit()

def rDep(depList=[]):
    if len(depList) != 0:
        for i in depList:
            if i in libraries:
                if os.path.exists(PYTHONPATH + i + ".py"):
                    os.remove(PYTHONPATH + i + ".py")
                    print(f"Library '{i}' was already installed, reinstalling...")
                os.system("wget -q " + LSources[libraries.index(i)])
                os.system("mv " + i + ".py " + PYTHONPATH)
                if os.path.exists(PYTHONPATH + i + ".py"):
                    print(f"Library '{i}' was installed successfully!")
                else:
                    print(f"Library '{i}' failed to installed")
            else:
                print(f"Library '{i}' is not in the main repository")
sys.argv.pop(0)

if len(sys.argv) == 0 or "--help" in sys.argv:
    print("Usage: fpac [keyword] [packages]")
    print()
    print("keywords:")
    print("install - Installs all specified packages")
    print("remove  - Removes all specified packages")
    print("search  - Searches for a specific package")
    print("check   - Checks if specified packages are installed")
    print("lib     - Lists all of a package's dependencies")
    print("list    - Lists all available packages")
    print("version - Prints the current version")

if len(sys.argv) == 1:
    if sys.argv[0] == "list":
        for i in packages:
            print(i)
    elif sys.argv[0] == "version":
        print(version)

if len(sys.argv) > 1:
    if sys.argv[0] == "install":
        for i in sys.argv[1:]:
            if i in packages:
                rDep(links[packages.index(i)])
                if not os.path.exists("/usr/bin/" + i):
                    os.system(f"wget -q {sources[packages.index(i)]}")
                    os.system(f"chmod +x {i}")
                    os.system(f"sudo mv {i} /usr/bin/")
                    print(f"Package '{i}' was installed!")
                else:
                    print(f"Package '{i}' is already installed, reinstalling...")
                    os.system(f"sudo rm /usr/bin/{i}")
                    os.system(f"wget -q {sources[packages.index(i)]}")
                    os.system(f"chmod +x {i}")
                    os.system(f"sudo mv {i} /usr/bin/")
            else:
                print(f"Package '{i}' is not in the main repository")
    
    elif sys.argv[0] == "remove":
        for i in sys.argv[1:]:
            if i in packages:
                if os.path.exists("/usr/bin/" + i):
                    os.system(f"sudo rm /usr/bin/{i}")
                    if os.path.exists("/usr/bin/" + i):
                        print(f"Package '{i}' was not removed successfully")
                    else:
                        print(f"Package '{i}' was removed successfully")
                else:
                    print(f"Package '{i}' is not installed")
            else:
                print(f"Package '{i}' is not in the main repository")
    
    elif sys.argv[0] == "check":
        for i in sys.argv[1:]:
            if i in packages:
                if os.path.exists("/usr/bin/" + i):
                    print(f"Package '{i}' is installed")
                else:
                    print(f"Package '{i}' is not installed")
            else:
                print(f"Package '{i}' is not in the main repository")
    elif sys.argv[0] == "lib":
        if sys.argv[1] in packages:
            if len(links[packages.index(sys.argv[1])]) != 0:
                print("\n".join(links[packages.index(sys.argv[1])]))
            else:
                print("Package has no dependencies!")
        else:
            print(f"Package '{sys.argv[1]}' is not in the main repository")
    
    elif sys.argv[0] == "search":
        for i in packages:
            if sys.argv[1] in i:
                print(i.replace(sys.argv[1],Fore.RED + sys.argv[1] + Fore.RESET))
